# Production Docker Compose for Varta-AI
# 
# Replace placeholders with your actual ECR repository URIs:
# export ECR_REPO_FRONTEND=123456789012.dkr.ecr.us-east-1.amazonaws.com/varta-ai-frontend:latest
# export ECR_REPO_BACKEND=123456789012.dkr.ecr.us-east-1.amazonaws.com/varta-ai-backend:latest

version: '3.8'

services:
  frontend:
    image: ${ECR_REPO_FRONTEND}
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  backend:
    image: ${ECR_REPO_BACKEND}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

networks:
  default:
    name: varta-ai-network